version: '3.8'

services:
  mysql-bach:
    image: mysql:8
    container_name: mysql-bach
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bach
      MYSQL_USER: batch_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-bach-data:/var/lib/mysql
      - ./sql/batch-schema.sql:/docker-entrypoint-initdb.d/batch-schema.sql

  mysql-restaurant:
    image: mysql:8
    container_name: mysql-restaurant
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: restaurant
      MYSQL_USER: restaurant_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql-restaurant-data:/var/lib/mysql
      - ./sql/restaurant-schema.sql:/docker-entrypoint-initdb.d/restaurant-schema.sql

volumes:
  mysql-bach-data:
  mysql-restaurant-data: