version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bach
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - batch-net

#  app:
#    build: src/main/java
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/batch
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 1234
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
#      SPRING_JPA_HIBERNATE_DDL_AUTO: none
#      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
#      SPRING_BATCH_INITIALIZE_SCHEMA: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    networks:
#      - batch-net

networks:
  batch-net:

volumes:
  mysql_db_data:
