spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bach?allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: batch_user
    password: 1234
    hikari:
      maximum-pool-size: 10
#  jpa:
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
#    properties:
#      hibernate:
#        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        dialect: org.hibernate.dialect.MySQLDialect

restaurant:
  datasource:
    url: jdbc:mysql://localhost:3307/restaurant?allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: restaurant_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

logging:
  level:
    org.springframework.batch: DEBUG