
CREATE TABLE restaurant (
                            id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                            service_name VARCHAR(255),
                            service_id VARCHAR(255),
                            local_code VARCHAR(255),
                            management_number VARCHAR(255),
                            permit_date DATE,
                            cancel_permit_date DATE,
                            business_status_code VARCHAR(255),
                            business_status_name VARCHAR(255),
                            detailed_business_status_code VARCHAR(255),
                            detailed_business_status_name VARCHAR(255),
                            close_date DATE,
                            suspend_start_date DATE,
                            suspend_end_date DATE,
                            reopen_date DATE,
                            phone VARCHAR(255),
                            area DECIMAL(10, 2),
                            postal_code VARCHAR(255),
                            full_address VARCHAR(255),
                            road_address VARCHAR(255),
                            road_postal_code VARCHAR(255),
                            business_name VARCHAR(255),
                            last_modified TIMESTAMP,
                            data_update_type VARCHAR(255),
                            data_update_date DATE,
                            business_type_name VARCHAR(255),
                            coordinate_x DECIMAL(10, 4),
                            coordinate_y DECIMAL(10, 4),
                            hygiene_business_type_name VARCHAR(255),
                            male_employee_count INT,
                            female_employee_count INT,
                            business_area_type_name VARCHAR(255),
                            grade_type_name VARCHAR(255),
                            water_supply_type_name VARCHAR(255),
                            total_employee_count INT,
                            head_office_employee_count INT,
                            factory_office_employee_count INT,
                            factory_sales_employee_count INT,
                            factory_production_employee_count INT,
                            building_ownership_type_name VARCHAR(255),
                            guarantee_amount DECIMAL(10, 2),
                            monthly_rent_amount DECIMAL(10, 2),
                            multi_use_facility_yn CHAR(1),
                            total_facility_size DECIMAL(10, 2),
                            traditional_business_number VARCHAR(255),
                            traditional_business_main_food VARCHAR(255),
                            homepage VARCHAR(255)
) ENGINE=InnoDB;

-- 인덱스 추가
CREATE INDEX idx_service_name ON restaurant(service_name);
CREATE INDEX idx_service_id ON restaurant(service_id);